swagger: "2.0"
info:
  version: "1.0"
  title: "awscodestar-project-a-api-lambda"
host: "si7zd23917.execute-api.us-west-2.amazonaws.com"
basePath: "/qa"
schemes:
- "https"
paths:
  /:
    get:
      responses: {}
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:239540765773:function:awscodestar-project-a-ms1-lambda-HelloWorld-2H20AIVJ5VUQ/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"
    post:
      responses: {}
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:239540765773:function:awscodestar-project-a-ms1-lambda-HelloWorld-2H20AIVJ5VUQ/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"
